trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  sshKey: 'vm-cloudwalker_key.pem' 

stages:

- stage: test
  jobs:
  - job: RunTests
    displayName: 'Run Unit Tests'
    steps:
    - script: echo "Running tests on the build agent"
      displayName: 'Echo Hello, world!'
    - script: mkdir data
      displayName: 'create directory'
    # install git
    - script: sudo apt-get install git
      displayName: 'installing git'
    # clone git repository
    - script: git clone Test-Driven-Development data
      displayName: 'clone git repository'

- stage: deploy
  jobs:
  - deployment: DeployWeb
    displayName: 'Deploy and Test on VM'
    pool:
      vmImage: 'ubuntu-latest'
    environment: 
      name: 'environment-aschmidt-cloudwalker'
      resourceName: vm-cloudwalker
      resourceType: virtualMachine
    strategy:
      runOnce:
        deploy:
          steps:
          - script: ls
            displayName: 'look at the given directories'
            
          
        # den SSH-Schlüssel herunterladen
          - task: DownloadSecureFile@1
            name: sshKey
            inputs:
              secureFile: $(sshKey)
          - script: |
              mkdir -p ~/.ssh
              cp $(sshKey.secureFilePath) ~/.ssh/vm-cloudwalker_key.pem
              chmod 400 ~/.ssh/vm-cloudwalker_key.pem
            displayName: 'setup ssh-key'
            
            # Temporär die Host-Key-Überprüfung deaktivieren
          - script: |
              echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
              chmod 600 ~/.ssh/config
            displayName: 'Disable Strict Host Key Checking'

            # auf VM kopieren
          - task: Bash@3
            displayName: 'copy data to vm'
            inputs:
              targetType: 'inline'
              script: 'scp -i ~/.ssh/vm-cloudwalker_key.pem -r data azureuser@4.184.201.242:cloudwalker'
          
      