trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  sshKey: 'vm-cloudwalker_key.pem' 


stages:

- stage: test
  jobs:
  - job: RunUnitTests
    displayName: 'run unittests'
    steps:
    - script: | 
        python -m venv .venv
        source .venv/bin/activate
      displayName: 'create virtual environment'
    - script: pip install -r requirements.txt
      displayName: 'install requirements'
    - script: python src/manage.py test src/lists
      displayName: 'run tests'
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Pipeline.Workspace)'
        artifact: 'Test-Driven-Development'
        publishLocation: 'pipeline'
      displayName: 'publish artifact'


- stage: deploy
  jobs:
  - deployment: DeployWeb
    displayName: 'Deploy and Test on VM'
    pool:
      vmImage: 'ubuntu-latest'
    environment: 
      name: 'environment-aschmidt-cloudwalker'
      resourceName: vm-cloudwalker
      resourceType: virtualMachine
    strategy:
      runOnce:
        deploy:
          steps:
          - script: ls
            displayName: 'look at the given directories'
            
          
        # den SSH-Schlüssel herunterladen
          - task: DownloadSecureFile@1
            name: sshKey
            inputs:
              secureFile: $(sshKey)
          - script: |
              mkdir -p $(Agent.TempDirectory)/.ssh
              cp $(sshKey.secureFilePath) $(Agent.TempDirectory)/.ssh/vm-cloudwalker_key.pem
              chmod 600 $(Agent.TempDirectory)/.ssh/vm-cloudwalker_key.pem
            displayName: 'setup ssh-key'

          # Temporär die Host-Key-Überprüfung deaktivieren
          - script: |
              echo -e "Host *\n\tStrictHostKeyChecking no\n" >> $(Agent.TempDirectory)/.ssh/config
              chmod 600 $(Agent.TempDirectory)/.ssh/config
            displayName: 'Disable Strict Host Key Checking'

          - script: scp Test-Driven-Development azureuser@4.184.201.242:cloudwalker/goat-book
            displayName: 'copy repository to azure vm'
