trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
- stage: clone
  jobs:
  - job: cloneRepository
    displayName: 'Clone the GitHub Repository'
    steps:
    - script: git clone Test-Drive-Development
      displayName: 'copy of Test-Driven-Development'

- stage: test
  jobs:
  - job: RunTests
    displayName: 'Run Unit Tests'
    steps:
    - script: echo "Running tests on the build agent"
      displayName: 'Echo Hello, world!'

- stage: deploy
  jobs:
  - deployment: DeployWeb
    displayName: 'Deploy and Test on VM'
    pool:
      vmImage: 'ubuntu-latest'
    environment: 
      name: 'environment-aschmidt-cloudwalker'
      resourceName: vm-cloudwalker
      resourceType: virtualMachine
    strategy:
      runOnce:
        deploy:
          steps:
          - script: ls
            displayName: 'look at the given directories'
          - script: cp Test-Driven-Development
            displayName: 'copy into vm'
          - script: ls
            displayName: 'check if directory exists'
      