trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:

- stage: test
  jobs:
  - job: RunTests
    displayName: 'Run Unit Tests'
    steps:
    - script: echo "Running tests on the build agent"
      displayName: 'Echo Hello, world!'

- stage: deploy
  jobs:
  - deployment: DeployWeb
    displayName: 'Deploy and Test on VM'
    pool:
      vmImage: 'ubuntu-latest'
    environment: 
      name: 'environment-aschmidt-cloudwalker'
      resourceName: vm-cloudwalker
      resourceType: virtualMachine
    strategy:
      runOnce:
        deploy:
          steps:
          - script: ls
            displayName: 'look at the given directories'
          - script: ssh -i vm-cloudwalker_key.pem azureuser@4.184.201.242
            displayName: 'log in into vm'
          - script: ls
            displayName: 'check if your in the vm'
      