trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  sshKey: 'vm-cloudwalker_key.pem' 

stages:

- stage: test
  jobs:
  - job: RunTests
    displayName: 'Run Unit Tests'
    steps:
    - script: echo "Running tests on the build agent"
      displayName: 'Echo Hello, world!'


- stage: deploy
  jobs:
  - deployment: DeployWeb
    displayName: 'Deploy and Test on VM'
    pool:
      vmImage: 'ubuntu-latest'
    environment: 
      name: 'environment-aschmidt-cloudwalker'
      resourceName: vm-cloudwalker
      resourceType: virtualMachine
    strategy:
      runOnce:
        deploy:
          steps:
          - script: ls
            displayName: 'look at the given directories'
            
          
        # den SSH-Schlüssel herunterladen
          - task: DownloadSecureFile@1
            name: sshKey
            inputs:
              secureFile: $(sshKey)
          - script: |
              mkdir -p $(Agent.TempDirectory)/.ssh
              cp $(sshKey.secureFilePath) $(Agent.TempDirectory)/.ssh/vm-cloudwalker_key.pem
              chmod 600 $(Agent.TempDirectory)/.ssh/vm-cloudwalker_key.pem
            displayName: 'setup ssh-key'

          # Temporär die Host-Key-Überprüfung deaktivieren
          - script: |
              echo -e "Host *\n\tStrictHostKeyChecking no\n" >> $(Agent.TempDirectory)/.ssh/config
              chmod 600 $(Agent.TempDirectory)/.ssh/config
            displayName: 'Disable Strict Host Key Checking'

     
          
            
          # install git
          - script: ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i $(Agent.TempDirectory)/.ssh/vm-cloudwalker_key.pem azureuser@4.184.201.242 'sudo apt-get update && sudo apt-get install -y git'
            displayName: 'installing git'
          # clone git repository
          - script: ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i $(Agent.TempDirectory)/.ssh/vm-cloudwalker_key.pem azureuser@4.184.201.242 'git clone https://github.com/AnnemarieSchmidt1806/Test-Driven-Development cloudwalker/goat-book'
            displayName: 'clone git repository'

      