# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest


stages:
- stage: test
  jobs:
    - job: RunTests
      displayName: 'Run Unit Tests'
      steps:
      - script: echo "Running tests on the build agent"
- stage: deploy
  jobs:
  - deployment: DeployWeb
    displayName: first Pipeline run
    pool:
      vmImage: 'Ubuntu-latest'
    # creates an environment if it doesn't exist
    environment: 
      name: 'environment-aschmidt-cloudwalker'
      resourceName: vm-cloudwalker
      resourceType: virtualMachine
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo Hello world